### ISSUE TITLE
No effect

### ISSUE THREAD

**Issue by Nabby109** [yuv420p10le/plexmediaserver_crack#2]
Plex Media Server for Windows, product version 1.40.2.8395-c67dce28e (up to date)
Located in Program Files (x86)

Plex Media Server.exe
MD5 83d9ac75624ac3dd87e711e26100d7a0
SHA-1 6dcca31f5e92cf85bf268ba772941ff94047f5a8
SHA-256 a7b5e2dcddd0bd29430386e6a1cf17e51c9e0c754e7925501c73f72aeeb4a892
SHA-512 a55f60941748da6effc816215c5db2b69275a061703da5dc50ec504e45a6d0e94fb33b270a421801e76a159a0f4f72b9c1dd60f13352a70dfa70d52353ac8a29

i5-3570K, Windows 10

I'm looking for the hardware accelerated transcoding option to show up to verify it's working. CPU has Intel HD 4000 with QuickSync. But the DLL seems to have no effect. Tried edde746's fork, without arguments returns a key error that architecture is AMD64. When using --platform Windows --arch x86_64 it returns signature not found. Manually searched for the sigs from his py script in my executable and they are not present. Are these methods version specific? Which Windows version have you tested with?

**Comment by yuv420p10le** [comment]
Hi, thanks for opening an issue.

Downloading [Plex Media Server (64-bit) for Windows](https://downloads.plex.tv/plex-media-server-new/1.40.2.8395-c67dce28e/windows/PlexMediaServer-1.40.2.8395-c67dce28e-x86_64.exe) and installing it, I can confirm that the signatures in both this repository and edde746's patcher, work.

The SHA-256 hash you provided does not match with the hash found on the installer I linked. I was able to find the SHA-256 you posted, and it corresponds to the x86 (32-bit) build of Plex Media Server. I should have clarified in the README that the crack only supports the 64-bit version of the Plex Media Server.

Do you have any reason to use the 32-bit version of Plex Media Server on your hardware? If you do, I will gladly add 32-bit support to the crack.

**Comment by Nabby109** [comment]
Thank you for the clarification. That resolves my issue. I have no specific reason to stay on 32 bit, only that my server has been running for 5 years and the 64 bit server has only been around for about 2 years, and I hadn't seen a need yet to switch it over. Now I do.

**Comment by yuv420p10le** [comment]
Gotcha. I'll release a 32-bit version of the crack soon as well

**Comment by yuv420p10le** [comment]
> Gotcha. I'll release a 32-bit version of the crack soon as well

I actually decided this isn't worth the effort. The 32-bit server happens to have the function we're hooking here as inlined, which would significantly increase the complexity of the crack.

I'll add a note to the README and marking this as WONTFIX for now; get the 64-bit version.
